image: docker:stable
pipelines:
  default:
    - parallel:
      - step:
          name: PHP 7.1
          caches:
            - docker
            - composer
            - pip
          services:
            - docker
          script:
            - apk add --no-cache py-pip bash rsync
            - rsync -avg ~/.composer/ ./build/composer/
            - pip install docker-compose
            - docker-compose -v
            - export PRIV_KEY=$MY_SSH_KEY
            - export PHP_VERSION=7.1
            - docker-compose up --abort-on-container-exit --exit-code-from test test
            - docker-compose down
            - rsync -avg ./build/composer/ ~/.composer/
      - step:
          name: PHP 5.6
          caches:
            - docker
            - composer
            - pip
          services:
            - docker
          script:
            - apk add --no-cache py-pip bash rsync
            - rsync -avg ~/.composer/ ./build/composer/
            - pip install docker-compose
            - docker-compose -v
            - export PRIV_KEY=$MY_SSH_KEY
            - export PHP_VERSION=5.6
            - docker-compose up --abort-on-container-exit --exit-code-from test test
            - docker-compose down
            - rsync -avg ./build/composer/ ~/.composer/
